export { ProductList } from './product-list/ProductList';
export { Header } from './header/Header';
export { ThisVacation } from './this-vacation/ThisVacation';
export { HeroCollection } from './hero-collection/HeroCollection';
export { CatalogList } from './catalog-list/CatalogList';
export { MiddleHero } from './middle-hero-collection/MiddleHero';
export { MoreToRead } from './more-to-read/MoreToRead';
export { About } from './about/About';
export { Footer } from './footer/Footer';
